export const players = [
    {
        id: '0DjBr1KRS6gin6RUQ2sa',
        hasPaidSubs: true,
        price: 6,
        goals: 10,
        team: 'Shadow Isles',
        points: 50,
        assists: 0,
        position: 'MIDFIELDER',
        name: 'Karthus',
        previousScore: 230
    },
    {
        id: '0F9SXBJBDlDuudHXlHjI',
        previousScore: 5,
        position: 'MIDFIELDER',
        goals: 16,
        points: 80,
        hasPaidSubs: true,
        price: 5,
        assists: 0,
        name: 'Diana',
        team: 'Targon'
    },
    {
        id: '0dEVXgTYbWm2QwcGUqkI',
        points: 36,
        goals: 9,
        previousScore: 54,
        price: 6,
        hasPaidSubs: true,
        position: 'ATTACKER',
        name: 'Shaco',
        team: 'Runeterra',
        assists: 0
    },
    {
        id: '2VPZSuIpfL79nM0hOYvk',
        team: 'Runeterra',
        price: 6,
        position: 'MIDFIELDER',
        points: 40,
        hasPaidSubs: true,
        name: 'Nocturne',
        goals: 8,
        assists: 0,
        previousScore: 56
    },
    {
        id: '2glwlX3EG60kglhUQqzs',
        points: 24,
        position: 'ATTACKER',
        price: 6,
        name: 'Lucian',
        assists: 0,
        previousScore: 86,
        goals: 6,
        team: 'Runeterra'
    },
    {
        id: '2t238m0yXJTtmskJPt5i',
        points: 25,
        previousScore: 13,
        name: 'Nunu',
        position: 'MIDFIELDER',
        assists: 0,
        goals: 5,
        team: 'Freljord',
        price: 6
    },
    {
        id: '2v3DRDtkE64Secci6XSv',
        goals: 11,
        assists: 0,
        team: 'Shurima',
        price: 3,
        name: 'Sivir',
        points: 44,
        previousScore: 20,
        position: 'ATTACKER'
    },
    {
        id: '33gnaUyH05VKWfrwVoA8',
        price: 3,
        name: 'Irelia',
        goals: 11,
        previousScore: 15,
        points: 44,
        assists: 0,
        position: 'ATTACKER',
        team: 'Ionia'
    },
    {
        id: '3VDTCHDtvAFlpDBE0g21',
        price: 2,
        previousScore: 5,
        goals: 8,
        points: 38,
        assists: 2,
        name: 'Veigar',
        position: 'ATTACKER',
        team: 'Bandle City'
    },
    {
        id: '4iCP6OT1LBYfpkhNoAww',
        assists: 5,
        goals: 8,
        previousScore: 23,
        team: 'Ixtal',
        name: 'Rengar',
        position: 'ATTACKER',
        points: 59,
        price: 3
    },
    {
        id: '56cmpQXro3OMKc46Sr05',
        position: 'DEFENDER',
        name: 'Jayce',
        team: 'Piltover',
        price: 8,
        previousScore: 81,
        points: 46,
        goals: 5,
        assists: 0
    },
    {
        id: '576DR6kjJu6gc0WDYawj',
        assists: 0,
        points: 34,
        position: 'DEFENDER',
        team: 'Ixtal',
        price: 3,
        previousScore: 15,
        name: 'Neeko',
        goals: 5
    },
    {
        id: '58odAZp5Pab1mzXLdHyT',
        price: 3,
        goals: 13,
        points: 94,
        position: 'DEFENDER',
        previousScore: 13,
        assists: 0,
        team: 'Targon',
        name: 'Soraka'
    },
    {
        id: '5EMoFM5Mv9rFezMOP8g0',
        price: 6,
        points: 20,
        position: 'MIDFIELDER',
        previousScore: 35,
        assists: 0,
        name: 'Kindred',
        team: 'Runeterra',
        goals: 4
    },
    {
        id: '5LOoI7p7E17emCW481OA',
        previousScore: 21,
        goals: 6,
        team: 'Targon',
        price: 3,
        assists: 0,
        name: 'Taric',
        position: 'DEFENDER',
        points: 52
    },
    {
        id: '5Sl4oMa5XAqTrZUfBnAG',
        previousScore: 23,
        name: 'Kai\'Sa',
        position: 'ATTACKER',
        price: 4.5,
        points: 60,
        team: 'The Void',
        assists: 0,
        goals: 15
    },
    {
        id: '6661AVXG6DgIcHuUEdeF',
        position: 'MIDFIELDER',
        assists: 0,
        points: 42,
        previousScore: 15,
        goals: 9,
        name: 'Yorick',
        team: 'Shadow Isles',
        price: 4
    },
    {
        id: '66GqV7f1XD96zvecTqht',
        goals: 18,
        points: 124,
        assists: 0,
        team: 'Demacia',
        name: 'Kayle',
        position: 'DEFENDER',
        previousScore: 27,
        price: 5
    },
    {
        id: '6BGut7yPRAJKnEUzbDf4',
        team: 'Noxus',
        price: 5,
        goals: 5,
        previousScore: 230,
        points: 20,
        position: 'ATTACKER',
        name: 'Draven',
        assists: 0
    },
    {
        id: '6BuBNdutgo8qstcDLta3',
        position: 'MIDFIELDER',
        points: 20,
        price: 5,
        previousScore: 78,
        team: 'Noxus',
        name: 'Swain',
        assists: 0,
        goals: 4
    },
    {
        id: '71PEv9vqPBWqE099PAfD',
        goals: 7,
        assists: 0,
        previousScore: 13,
        name: 'Janna',
        team: 'Zaun',
        price: 3,
        points: 58,
        position: 'DEFENDER'
    },
    {
        id: '7eWnqzriYYzKz7BuJrs5',
        goals: 0,
        assists: 0,
        team: 'Runeterra',
        previousScore: 13,
        points: 16,
        position: 'DEFENDER',
        name: 'Senna',
        price: 6
    },
    {
        id: '8H1GwHMbL9AxYIeWdV8X',
        position: 'MIDFIELDER',
        name: 'Cassiopeia',
        price: 5,
        assists: 3,
        previousScore: 13,
        points: 49,
        goals: 8,
        team: 'Noxus'
    },
    {
        id: '8y1elUwUhlhi6m0ZyAsU',
        team: 'Ionia',
        position: 'ATTACKER',
        points: 44,
        goals: 11,
        assists: 0,
        previousScore: 18,
        price: 1,
        name: 'Kayn'
    },
    {
        id: '9lhSy1Svn9BcgNf1AEOV',
        points: 54,
        assists: 0,
        name: 'Darius',
        position: 'GOALKEEPER',
        team: 'Noxus',
        previousScore: 23,
        goals: 5,
        price: 5
    },
    {
        id: 'AA42AtjrUG6OBDA5fPnB',
        points: 76,
        assists: 0,
        goals: 19,
        price: 4,
        previousScore: 91,
        name: 'Kha\'zix',
        position: 'ATTACKER',
        team: 'The Void'
    },
    {
        id: 'AAP5hGMrhOnKrXGy4UIx',
        position: 'ATTACKER',
        points: 20,
        previousScore: 13,
        assists: 0,
        goals: 5,
        team: 'Freljord',
        price: 6,
        name: 'Ashe'
    },
    {
        id: 'Abtao7o7NF0gPrPzV8kL',
        goals: 18,
        previousScore: 1000,
        name: 'Singed',
        points: 72,
        position: 'ATTACKER',
        team: 'Zaun',
        assists: 0,
        price: 15
    },
    {
        id: 'AhXWKh6W27hnkgWfPH8H',
        goals: 0,
        name: 'Lulu',
        position: 'DEFENDER',
        team: 'Bandle City',
        assists: 3,
        previousScore: 0,
        price: 2,
        points: 9
    },
    {
        id: 'AzKRu9v39TS8Vs1UcdiT',
        assists: 0,
        goals: 6,
        previousScore: 80,
        name: 'annie',
        points: 30,
        team: 'Runeterra',
        price: 5,
        position: 'MIDFIELDER'
    },
    {
        id: 'BEtlqEta8BgauR1gUiV6',
        position: 'DEFENDER',
        assists: 0,
        points: 16,
        team: 'Runeterra',
        price: 6,
        goals: 0,
        previousScore: 32,
        name: 'Tahm Kench'
    },
    {
        id: 'BIMySL1C05jOKfALjvdu',
        goals: 0,
        team: 'Noxus',
        assists: 12,
        name: 'Kled',
        points: 52,
        position: 'DEFENDER',
        price: 5,
        previousScore: 23
    },
    {
        id: 'BKfSb52au1uKlLV6q7oE',
        position: 'ATTACKER',
        previousScore: 29,
        name: 'Master Yi',
        price: 5,
        team: 'Ionia',
        goals: 14,
        assists: 0,
        points: 56
    },
    {
        id: 'BSVJRhJ9RLaeZ3K68fWl',
        name: 'Anivia',
        points: 96,
        position: 'GOALKEEPER',
        previousScore: 50,
        team: 'Freljord',
        price: 6,
        goals: 5,
        assists: 14
    },
    {
        id: 'C518s4dsQJ08pyvDwSW4',
        team: 'The Void',
        position: 'ATTACKER',
        price: 6.2,
        assists: 0,
        name: 'Kog\'Maw',
        goals: 18,
        points: 72,
        previousScore: 13
    },
    {
        id: 'DWOVybIOqmFwhzbP1ABj',
        price: 3,
        name: 'Ziggs',
        points: 0,
        team: 'Zaun',
        assists: 0,
        previousScore: 58,
        goals: 0,
        position: 'MIDFIELDER'
    },
    {
        id: 'EDvAtuiEFNHIeQ64S4DZ',
        assists: 0,
        price: 6,
        previousScore: 19,
        points: 0,
        name: 'Fiddlesticks',
        position: 'ATTACKER',
        goals: 0,
        team: 'Runeterra'
    },
    {
        id: 'EJ95CXP6Mt462UwBLP3K',
        price: 3,
        team: 'Shurima',
        previousScore: 75,
        goals: 5,
        name: 'Skarner',
        position: 'MIDFIELDER',
        assists: 0,
        points: 25
    },
    {
        id: 'EOEEMuYn5FslyEhc2zwY',
        price: 6,
        name: 'Bard',
        team: 'Runeterra',
        points: 25,
        goals: 5,
        assists: 0,
        previousScore: 17,
        position: 'MIDFIELDER'
    },
    {
        id: 'ETbGgmcOsEyczWx4S1j2',
        points: 12,
        name: 'Kassadin',
        position: 'MIDFIELDER',
        previousScore: 236,
        price: 7,
        goals: 0,
        team: 'The Void',
        assists: 4
    },
    {
        id: 'FzcwhgwN0br9nJsRnS3a',
        team: 'Ixtal',
        assists: 5,
        price: 13,
        name: 'Malphite',
        previousScore: 25,
        position: 'GOALKEEPER',
        points: 87,
        goals: 8
    },
    {
        id: 'G6cG8BnQyN2z6ZXoZiKZ',
        assists: 0,
        previousScore: 1,
        goals: 8,
        name: 'Ornn',
        price: 6,
        position: 'DEFENDER',
        team: 'Freljord',
        points: 64
    },
    {
        id: 'G9bpqakSi8kFb4F75SiY',
        goals: 4,
        points: 16,
        position: 'ATTACKER',
        team: 'Piltover',
        price: 4,
        previousScore: 22,
        name: 'Caitlyn',
        assists: 0
    },
    {
        id: 'GLfEOiS2yfoS5mRh5GgF',
        price: 3,
        position: 'DEFENDER',
        goals: 0,
        previousScore: 64,
        name: 'Warwick',
        points: 16,
        assists: 0,
        team: 'Zaun'
    },
    {
        id: 'HWl8BlHURojceO8ak2Bo',
        previousScore: 3,
        points: 0,
        name: 'Aphelios',
        team: 'Targon',
        assists: 0,
        position: 'ATTACKER',
        goals: 0,
        price: 3
    },
    {
        id: 'I2XrHRdscVUhyXPNwJtn',
        points: 0,
        price: 6,
        position: 'MIDFIELDER',
        assists: 0,
        team: 'Runeterra',
        previousScore: 48,
        goals: 0,
        name: 'Jax'
    },
    {
        id: 'IAqruivPGrK5eQB8IP8h',
        assists: 0,
        price: 8.5,
        previousScore: 34,
        position: 'GOALKEEPER',
        points: 54,
        team: 'Zaun',
        name: 'Blitzcrank',
        goals: 5
    },
    {
        id: 'IpXn9wt9RI5oMn0KwqdG',
        points: 36,
        goals: 0,
        price: 5,
        name: 'Katarina',
        previousScore: 15,
        position: 'MIDFIELDER',
        assists: 12,
        team: 'Noxus'
    },
    {
        id: 'IubcIU1MbErgVz5tsvsR',
        team: 'The Void',
        assists: 4,
        previousScore: 56,
        price: 6.2,
        name: 'Malzahar',
        points: 12,
        goals: 0,
        position: 'MIDFIELDER'
    },
    {
        id: 'IuuaKcdmypRf9586WpWd',
        position: 'ATTACKER',
        assists: 0,
        price: 3,
        previousScore: 30,
        team: 'Ionia',
        name: 'Jhin',
        goals: 10,
        points: 40
    },
    {
        id: 'JDGJ4N1BOhBneNlNWYGf',
        position: 'MIDFIELDER',
        goals: 4,
        previousScore: 32,
        assists: 1,
        team: 'Shurima',
        price: 3,
        name: 'Taliyah',
        points: 23
    },
    {
        id: 'JPoJ0fKriU76VA7uLHo4',
        points: 88,
        price: 6,
        assists: 0,
        previousScore: 15,
        goals: 12,
        position: 'DEFENDER',
        name: 'Sona',
        team: 'Demacia'
    },
    {
        id: 'K66q9xuTzSN5NDofghxM',
        team: 'Demacia',
        price: 9,
        previousScore: 2,
        assists: 6,
        name: 'Galio',
        points: 112,
        position: 'DEFENDER',
        goals: 13
    },
    {
        id: 'KEgQKSlhCd7JQ5ZiN9Q6',
        name: 'Volibear',
        price: 3,
        team: 'Freljord',
        points: 61,
        goals: 8,
        assists: 7,
        position: 'MIDFIELDER',
        previousScore: 7
    },
    {
        id: 'KdgWylwUciHbTePbMknJ',
        goals: 9,
        team: 'Bilgewater',
        previousScore: 13,
        points: 76,
        position: 'DEFENDER',
        assists: 2,
        price: 6,
        name: 'Nautilus'
    },
    {
        id: 'KuIQu36qY9pDBk5Gakm4',
        position: 'GOALKEEPER',
        price: 4,
        assists: 0,
        points: 96,
        previousScore: 5,
        goals: 14,
        name: 'Gankplank',
        team: 'Bilgewater'
    },
    {
        id: 'LJJ14edMABEFDEWSv3m5',
        points: -3,
        previousScore: 34,
        position: 'ATTACKER',
        price: 6,
        goals: 0,
        team: 'Runeterra',
        name: 'Evelynn',
        assists: 3
    },
    {
        id: 'LMyOtI3LVffGekcTEyhx',
        price: 6.2,
        previousScore: 32,
        points: 31,
        name: 'Rek\'sai',
        assists: 1,
        team: 'The Void',
        position: 'DEFENDER',
        goals: 0
    },
    {
        id: 'LhSAYvDFWlBtMhjcBihH',
        goals: 0,
        team: 'Demacia',
        position: 'MIDFIELDER',
        points: 0,
        price: 6,
        name: 'Sylas',
        assists: 0,
        previousScore: 9
    },
    {
        id: 'MHGlos6LK2BzsMVCStsP',
        position: 'ATTACKER',
        team: 'Ionia',
        name: 'Wukong',
        price: 5,
        goals: 0,
        points: 18,
        previousScore: 25,
        assists: 6
    },
    {
        id: 'MJvHfmOIc0MAhBTYdc82',
        goals: 4,
        previousScore: 8,
        price: 4,
        team: 'Bilgewater',
        points: 40,
        position: 'DEFENDER',
        assists: 0,
        name: 'Graves'
    },
    {
        id: 'MbxGXZWPadtdHi7WJ6SF',
        assists: 0,
        points: 70,
        position: 'DEFENDER',
        previousScore: 1,
        team: 'Demacia',
        goals: 9,
        price: 3,
        name: 'Lux'
    },
    {
        id: 'MkzZO1FqRgMK4GYJdHZb',
        points: 23,
        previousScore: 32,
        goals: 7,
        assists: 0,
        team: 'Shadow Isles',
        name: 'Kalista',
        position: 'MIDFIELDER',
        price: 6
    },
    {
        id: 'MzOJoQzW7Jdj53e6n3zn',
        team: 'The Void',
        name: 'Cho Gath',
        goals: 0,
        position: 'GOALKEEPER',
        assists: 0,
        price: 4.5,
        previousScore: 32,
        points: 24
    },
    {
        id: 'Oaua5Yidt7nkWfbidUlS',
        previousScore: 15,
        assists: 6,
        goals: 0,
        name: 'Urgot',
        position: 'DEFENDER',
        points: 34,
        price: 3,
        team: 'Zaun'
    },
    {
        id: 'P2ZcPiQHMJbDj2flWUod',
        points: 24,
        assists: 8,
        previousScore: 71,
        team: 'Ionia',
        goals: 0,
        name: 'Varus',
        price: 5,
        position: 'ATTACKER'
    },
    {
        id: 'PqqddFYVOxqbt9vmJzwO',
        position: 'ATTACKER',
        goals: 10,
        price: 6,
        assists: 4,
        points: 54,
        team: 'Shadow Isles',
        previousScore: 100,
        name: 'Hecarim'
    },
    {
        id: 'PtsrBBcGVJTBQrkddVOr',
        previousScore: 1556,
        assists: 0,
        points: 4,
        position: 'ATTACKER',
        price: 7,
        goals: 1,
        team: 'Freljord',
        name: 'Tryndamere'
    },
    {
        id: 'QREySUja4BXbZIcjO15o',
        previousScore: 0,
        team: 'Bandle City',
        assists: 4,
        points: 60,
        price: 2,
        goals: 8,
        name: 'Corki',
        position: 'GOALKEEPER'
    },
    {
        id: 'QS6uyxf36h9ObKskGSQf',
        assists: 0,
        goals: 5,
        team: 'Ixtal',
        points: 20,
        position: 'ATTACKER',
        previousScore: 15,
        price: 3,
        name: 'Qiyana'
    },
    {
        id: 'QUtlHCFr4gNTdSRjpdUE',
        position: 'ATTACKER',
        team: 'Freljord',
        price: 6,
        goals: 0,
        name: 'Olaf',
        assists: 0,
        previousScore: 20,
        points: 0
    },
    {
        id: 'QZWlP7gLLyQ6gJxfz4S6',
        points: 41,
        name: 'Orianna',
        goals: 1,
        previousScore: 57,
        team: 'Piltover',
        price: 4,
        position: 'MIDFIELDER',
        assists: 8
    },
    {
        id: 'QrFaANeerOyN2AvvYFxH',
        name: 'Yuumi',
        price: 2,
        points: -12,
        position: 'ATTACKER',
        previousScore: 5,
        team: 'Bandle City',
        goals: 0,
        assists: 0
    },
    {
        id: 'QyIyiOLvZTVfm6iG5vnX',
        assists: 4,
        position: 'MIDFIELDER',
        price: 5,
        previousScore: 15,
        name: 'Viktor',
        team: 'Zaun',
        goals: 0,
        points: 12
    },
    {
        id: 'RFAg6pqfkp7Wnw2FsEIB',
        points: 12,
        previousScore: 13,
        price: 2,
        position: 'MIDFIELDER',
        goals: 0,
        assists: 0,
        team: 'Bandle City',
        name: 'Tristana'
    },
    {
        id: 'RblNGl3ja9aQStogau1s',
        previousScore: 23,
        assists: 6,
        position: 'MIDFIELDER',
        points: 18,
        team: 'Ixtal',
        price: 3,
        name: 'Nidalee',
        goals: 0
    },
    {
        id: 'SRzxzrUZYLUK0Io7IBzz',
        position: 'DEFENDER',
        price: 6,
        name: 'Thresh',
        points: 37,
        team: 'Shadow Isles',
        goals: 0,
        previousScore: 32,
        assists: 3
    },
    {
        id: 'SrmXVNyIJoRYt1Kk5L02',
        team: 'Ionia',
        position: 'ATTACKER',
        assists: 8,
        goals: 0,
        price: 3,
        points: 24,
        previousScore: 3,
        name: 'Ahri'
    },
    {
        id: 'Ss025V3H9LVvR2SEbUkF',
        position: 'DEFENDER',
        points: 28,
        goals: 2,
        team: 'Shurima',
        price: 3,
        name: 'Nasus',
        assists: 0,
        previousScore: 53
    },
    {
        id: 'TLr19UHm9qB48vvlteKf',
        name: 'Xerath',
        goals: 6,
        points: 39,
        team: 'Shurima',
        price: 3,
        previousScore: 189,
        assists: 3,
        position: 'MIDFIELDER'
    },
    {
        id: 'TxTB6IlUS7n5kxPMTOQt',
        points: 24,
        team: 'Noxus',
        assists: 8,
        goals: 0,
        previousScore: 25,
        position: 'ATTACKER',
        price: 5,
        name: 'Riven'
    },
    {
        id: 'UOwxYqmjTuklGZp3OaPK',
        previousScore: 15,
        price: 5,
        name: 'Rakan',
        goals: 0,
        position: 'DEFENDER',
        team: 'Ionia',
        points: 43,
        assists: 9
    },
    {
        id: 'UTQWiJeeiBkRsh0MkBOM',
        team: 'Noxus',
        points: 34,
        price: 5,
        assists: 6,
        goals: 0,
        previousScore: 53,
        name: 'Mordekaiser',
        position: 'DEFENDER'
    },
    {
        id: 'WAVavGHeSerw31jv2QvO',
        position: 'DEFENDER',
        price: 5,
        assists: 0,
        name: 'Sion',
        goals: 0,
        previousScore: 17,
        points: 28,
        team: 'Noxus'
    },
    {
        id: 'WJLzkn1sZEkGh2sGz4p6',
        previousScore: 22,
        points: 22,
        goals: 4,
        price: 6,
        position: 'ATTACKER',
        team: 'Bilgewater',
        assists: 2,
        name: 'Miss Fortune'
    },
    {
        id: 'WL9b20sfjU1HiQFcB8E3',
        name: 'Alistar',
        points: 24,
        assists: 0,
        previousScore: 12,
        position: 'GOALKEEPER',
        team: 'Runeterra',
        price: 5,
        goals: 0
    },
    {
        id: 'WSAE3nhivReEcGsHRwSv',
        goals: 0,
        previousScore: 19,
        name: 'Vladamir',
        price: 4,
        position: 'MIDFIELDER',
        assists: 0,
        points: -12,
        team: 'Noxus'
    },
    {
        id: 'WkQKCehXOfwGdvAeoKrU',
        goals: 0,
        name: 'Azir',
        points: 0,
        previousScore: 12,
        team: 'Shurima',
        assists: 0,
        price: 3,
        position: 'MIDFIELDER'
    },
    {
        id: 'X2YXcj6jHicbrmAjSEEt',
        previousScore: 2,
        points: 16,
        position: 'DEFENDER',
        team: 'Freljord',
        assists: 0,
        price: 3,
        name: 'Udyr',
        goals: 0
    },
    {
        id: 'X8jbCv8MU5PTAWtVd5IV',
        points: 55,
        team: 'Demacia',
        name: 'Xin Zhao',
        assists: 0,
        goals: 11,
        previousScore: 13,
        price: 6,
        position: 'MIDFIELDER'
    },
    {
        id: 'Ya6yqHAzSCTnVx3E7B8S',
        price: 3,
        points: 16,
        previousScore: 32,
        assists: 0,
        name: 'Zac',
        goals: 0,
        team: 'Zaun',
        position: 'DEFENDER'
    },
    {
        id: 'Zlpchou4yxk5BGsNphMe',
        price: 5,
        points: 0,
        name: 'Syndra',
        previousScore: 7,
        team: 'Ionia',
        assists: 0,
        position: 'ATTACKER',
        goals: 0
    },
    {
        id: 'a5bV526PoMHnWVvyZOx9',
        name: 'Vel\'koz',
        goals: 0,
        price: 8.5,
        position: 'MIDFIELDER',
        previousScore: 57,
        team: 'The Void',
        assists: 0,
        points: -12
    },
    {
        id: 'aQGQnBC9dOSKTufX6BUl',
        previousScore: 0,
        assists: 0,
        team: 'Noxus',
        position: 'GOALKEEPER',
        price: 4,
        goals: 0,
        name: 'test',
        points: 0
    },
    {
        id: 'aZxXRzVyRF35Nhf6zgoI',
        points: 24,
        team: 'Bandle City',
        assists: 4,
        price: 2,
        position: 'DEFENDER',
        goals: 2,
        previousScore: 15,
        name: 'Rumble'
    },
    {
        id: 'b9LCiio8FgiJiqFoC1pR',
        assists: 3,
        goals: 0,
        previousScore: 18,
        team: 'Bilgewater',
        price: 7,
        name: 'Illaoi',
        position: 'MIDFIELDER',
        points: 21
    },
    {
        id: 'eptqi4NAwrnYzhRIBMvC',
        position: 'DEFENDER',
        goals: 0,
        price: 5,
        previousScore: 13,
        points: 24,
        assists: 4,
        team: 'Targon',
        name: 'Leona'
    },
    {
        id: 'fQ4QZIniB6caFW88vuaS',
        team: 'Targon',
        position: 'GOALKEEPER',
        points: 18,
        price: 5,
        assists: 10,
        previousScore: 50,
        goals: 0,
        name: 'Pantheon'
    },
    {
        id: 'fRqFiq5utQf4yPBxhvDV',
        goals: 0,
        name: 'Maokai',
        previousScore: 18,
        position: 'DEFENDER',
        assists: 3,
        price: 6,
        team: 'Shadow Isles',
        points: 22
    },
    {
        id: 'fSnmIvBxXkwL0DP3ANWI',
        name: 'Lissandra',
        points: 12,
        price: 6,
        previousScore: 40,
        goals: 0,
        team: 'Freljord',
        assists: 0,
        position: 'ATTACKER'
    },
    {
        id: 'fZxvQVer4phrmWFJGObo',
        points: 27,
        previousScore: 18,
        team: 'Piltover',
        price: 8,
        goals: 0,
        assists: 9,
        name: 'Ezreal',
        position: 'ATTACKER'
    },
    {
        id: 'faoemOnNadDOPqKsHtb5',
        name: 'Morgana',
        goals: 0,
        points: 0,
        price: 4,
        team: 'Demacia',
        position: 'MIDFIELDER',
        assists: 0,
        previousScore: 13
    },
    {
        id: 'fp93uKDh9vP4DA2sWLCo',
        points: 0,
        assists: 0,
        price: 4,
        name: 'Talon',
        position: 'ATTACKER',
        previousScore: 35,
        team: 'Noxus',
        goals: 0
    },
    {
        id: 'ftAlXFzlbaw660RLb0OP',
        team: 'Freljord',
        assists: 0,
        previousScore: 4,
        points: 16,
        goals: 0,
        price: 6,
        name: 'Gragas',
        position: 'DEFENDER'
    },
    {
        id: 'fxs4XKel9JZBlDAmhYyp',
        price: 6,
        assists: 1,
        previousScore: 42,
        team: 'Shadow Isles',
        goals: 0,
        name: 'Elise',
        points: 25,
        position: 'GOALKEEPER'
    },
    {
        id: 'geKwHanYrbkyPUpAmCai',
        goals: 0,
        position: 'DEFENDER',
        price: 3,
        name: 'Renekton',
        previousScore: 19,
        points: 12,
        assists: 4,
        team: 'Shurima'
    },
    {
        id: 'hBqk3AChNKcNaCdjDJVP',
        position: 'DEFENDER',
        name: 'Braum',
        team: 'Freljord',
        price: 6,
        points: 0,
        goals: 0,
        previousScore: 8,
        assists: 4
    },
    {
        id: 'hHG1pEq8lpI9GnWm35tT',
        position: 'MIDFIELDER',
        goals: 0,
        name: 'Yasuo',
        team: 'Ionia',
        points: 0,
        previousScore: 13,
        assists: 0,
        price: 5
    },
    {
        id: 'hOgiX6TgffhREqEwPqji',
        name: 'Garen',
        team: 'Demacia',
        price: 3,
        points: 12,
        goals: 0,
        position: 'MIDFIELDER',
        assists: 0,
        previousScore: 15
    },
    {
        id: 'hhVCH5sxRfrKTiCh0gel',
        price: 5,
        points: 0,
        previousScore: 29,
        goals: 0,
        name: 'Lee Sin',
        assists: 0,
        team: 'Ionia',
        position: 'ATTACKER'
    },
    {
        id: 'hpyKJCGsEXw9CtC1mWSk',
        points: 84,
        price: 6,
        position: 'ATTACKER',
        assists: 8,
        team: 'Demacia',
        previousScore: 19,
        name: 'Quinn',
        goals: 15
    },
    {
        id: 'j1Rz5qAgoEBzPQGYmc1x',
        price: 3,
        points: 12,
        goals: 0,
        name: 'Akali',
        position: 'GOALKEEPER',
        previousScore: 3,
        assists: 0,
        team: 'Ionia'
    },
    {
        id: 'jkk0ZEBjH9nIzA6TC5P7',
        goals: 0,
        position: 'ATTACKER',
        team: 'Ionia',
        assists: 0,
        price: 5,
        previousScore: 25,
        name: 'Zed',
        points: 0
    },
    {
        id: 'joHsDYVoB8afcedpMgys',
        name: 'Zilean',
        position: 'MIDFIELDER',
        points: 30,
        assists: 10,
        previousScore: 56,
        goals: 0,
        team: 'Runeterra',
        price: 6
    },
    {
        id: 'k4Ri9vENM8mQfb6Ocw8Q',
        name: 'Amumu',
        points: 27,
        assists: 1,
        goals: 0,
        team: 'Shurima',
        previousScore: 13,
        position: 'GOALKEEPER',
        price: 3
    },
    {
        id: 'kAh8Rqr9gJhW6Ia93PsK',
        points: 9,
        assists: 3,
        name: '|yra',
        price: 3,
        previousScore: 15,
        position: 'MIDFIELDER',
        team: 'Ixtal',
        goals: 0
    },
    {
        id: 'kJF6acsCpdpKvccaZa4O',
        goals: 0,
        points: 16,
        assists: 0,
        price: 5,
        position: 'DEFENDER',
        previousScore: 15,
        name: 'Sett',
        team: 'Ionia'
    },
    {
        id: 'kVDH0Hw8D96hj3w5INKO',
        points: 28,
        goals: 0,
        position: 'DEFENDER',
        name: 'Shen',
        previousScore: 23,
        price: 5,
        assists: 0,
        team: 'Ionia'
    },
    {
        id: 'kff2H25Ma5BebA5nGCvW',
        previousScore: 13,
        points: 4,
        name: 'Dr Mundo',
        goals: 0,
        assists: 0,
        team: 'Zaun',
        price: 4,
        position: 'DEFENDER'
    },
    {
        id: 'khHCpjXtJQ4YxCiW5ZbM',
        team: 'Zaun',
        previousScore: 19,
        price: 17,
        position: 'MIDFIELDER',
        points: 18,
        goals: 0,
        name: 'Ekko',
        assists: 2
    },
    {
        id: 'm6kZLsnEtFdNlrqqOPBw',
        points: 18,
        team: 'Zaun',
        previousScore: 45,
        goals: 0,
        assists: 6,
        price: 3,
        position: 'ATTACKER',
        name: 'Jinx'
    },
    {
        id: 'mAnqSGO1Ly4BPq1wXsmZ',
        price: 3,
        previousScore: 32,
        name: 'Rammus',
        assists: 2,
        team: 'Shurima',
        position: 'DEFENDER',
        goals: 0,
        points: 6
    },
    {
        id: 'mBM4dHWs61OCy1M9Vgz6',
        previousScore: 32,
        assists: 12,
        name: 'Ryze',
        price: 6,
        position: 'MIDFIELDER',
        points: 36,
        team: 'Runeterra',
        goals: 0
    },
    {
        id: 'mIczSlEQNA09lD9FUegb',
        previousScore: 13,
        team: 'Bandle City',
        goals: 8,
        assists: 0,
        name: 'Teemo',
        points: 48,
        price: 2,
        position: 'DEFENDER'
    },
    {
        id: 'mnNkXxghWTkJbmtM6TAt',
        previousScore: 1,
        team: 'Bilgewater',
        goals: 0,
        price: 6,
        position: 'ATTACKER',
        assists: 0,
        points: 0,
        name: 'Twisted Fate'
    },
    {
        id: 'mwl5wWPyK3HgSJjv92JK',
        previousScore: 21,
        team: 'Demacia',
        goals: 0,
        position: 'MIDFIELDER',
        points: 9,
        assists: 7,
        name: 'Shyvana',
        price: 6
    },
    {
        id: 'o3rP68KSr1aiaVJEgHHZ',
        points: 16,
        name: 'Ivern',
        goals: 0,
        price: 3,
        team: 'Ionia',
        assists: 0,
        position: 'DEFENDER',
        previousScore: 22
    },
    {
        id: 'ogjBy5ufKb4Dblj5ZO3v',
        price: 6,
        previousScore: 13,
        goals: 0,
        points: 21,
        assists: 7,
        name: 'Vayne',
        team: 'Demacia',
        position: 'ATTACKER'
    },
    {
        id: 'ptCbfgjSWJFwT491s1BA',
        points: 33,
        goals: 0,
        previousScore: 13,
        price: 9,
        name: 'Fiora',
        assists: 3,
        team: 'Demacia',
        position: 'GOALKEEPER'
    },
    {
        id: 'q1goerwrSSKWawX909rY',
        goals: 0,
        previousScore: 35,
        position: 'ATTACKER',
        team: 'Freljord',
        assists: 12,
        price: 3,
        points: 36,
        name: 'Trundle'
    },
    {
        id: 'qMVisXKmLdH2UPkHU7nT',
        points: 0,
        team: 'Piltover',
        assists: 4,
        position: 'MIDFIELDER',
        goals: 0,
        previousScore: 18,
        name: 'Camille',
        price: 7
    },
    {
        id: 'qcLvN0QhhmfGfAei1gzD',
        name: 'Sejuani',
        team: 'Freljord',
        points: 30,
        assists: 10,
        price: 3,
        goals: 0,
        position: 'MIDFIELDER',
        previousScore: 5
    },
    {
        id: 's92ehAxIJpjaxwA3mxzg',
        price: 3,
        name: 'Jarvan IV',
        points: 15,
        position: 'ATTACKER',
        goals: 0,
        previousScore: 33,
        team: 'Demacia',
        assists: 5
    },
    {
        id: 'sRjF97WpDhM87Xx6dOoO',
        assists: 10,
        goals: 0,
        points: 30,
        previousScore: 13,
        price: 6,
        name: 'Gnar',
        team: 'Freljord',
        position: 'MIDFIELDER'
    },
    {
        id: 'sbV8CgScSdNsQz3Z3xld',
        team: 'Runeterra',
        price: 6,
        assists: 9,
        goals: 0,
        position: 'ATTACKER',
        name: 'Fizz',
        previousScore: 83,
        points: 27
    },
    {
        id: 'syOYfMGYdaDyyB02vK71',
        previousScore: 22,
        team: 'Bilgewater',
        position: 'MIDFIELDER',
        goals: 0,
        points: 9,
        assists: 3,
        price: 6,
        name: 'Pyke'
    },
    {
        id: 'szV97ZblucfPWwVZ2oGJ',
        team: 'Ionia',
        name: 'Kennen',
        price: 5,
        assists: 0,
        position: 'MIDFIELDER',
        points: 0,
        goals: 0,
        previousScore: 3
    },
    {
        id: 'tCWoVPQShbrAkcEEmyyn',
        goals: 15,
        previousScore: 3,
        name: 'Poppy',
        assists: 5,
        position: 'DEFENDER',
        price: 6,
        points: 121,
        team: 'Demacia'
    },
    {
        id: 'tK3bte9HcE9kpEXC8VBl',
        goals: 0,
        price: 6,
        position: 'DEFENDER',
        name: 'Nami',
        previousScore: 43,
        points: 28,
        team: 'Runeterra',
        assists: 0
    },
    {
        id: 'u0gcSJjpJF3lHZ08axRu',
        points: 0,
        assists: 0,
        price: 6,
        goals: 0,
        position: 'MIDFIELDER',
        name: 'Brand',
        team: 'Runeterra',
        previousScore: 75
    },
    {
        id: 'uPuy1DXGdYm9uQFj7X6J',
        points: 0,
        goals: 0,
        price: 3,
        position: 'ATTACKER',
        name: 'Twitch',
        team: 'Zaun',
        assists: 0,
        previousScore: 32
    },
    {
        id: 'vDG7lhe3BI5q61cjUwRK',
        goals: 0,
        position: 'GOALKEEPER',
        points: 39,
        assists: 5,
        previousScore: 290,
        team: 'Piltover',
        name: 'Heimerdinger',
        price: 8
    },
    {
        id: 'vtgd5WpnAOGwNDJrflsq',
        goals: 0,
        name: 'Karma',
        price: 3,
        team: 'Ionia',
        position: 'MIDFIELDER',
        points: 0,
        previousScore: 18,
        assists: 0
    },
    {
        id: 'wCrAXCI35ZHEq7a0mZvw',
        name: 'Aurelion Sol',
        team: 'Runeterra',
        price: 6,
        position: 'MIDFIELDER',
        assists: 0,
        goals: 0,
        previousScore: 53,
        points: 0
    },
    {
        id: 'xhdHRALVb6Czxbt9RynC',
        team: 'Runeterra',
        name: 'Aatrox',
        price: 5,
        position: 'DEFENDER',
        goals: 0,
        assists: 0,
        previousScore: 32,
        points: 16
    },
    {
        id: 'y7QfiBblqDrEV0itIpks',
        name: 'Zoe',
        assists: 7,
        points: 21,
        team: 'Targon',
        goals: 0,
        price: 5,
        position: 'DEFENDER',
        previousScore: 15
    },
    {
        id: 'yqwCXnIghRMhZc0sks0k',
        position: 'MIDFIELDER',
        previousScore: 25,
        name: 'Xayah',
        assists: 0,
        goals: 0,
        price: 5,
        team: 'Ionia',
        points: 0
    },
    {
        id: 'zw7467rWsitzbX6DdqNy',
        position: 'ATTACKER',
        assists: 0,
        team: 'Noxus',
        previousScore: 90,
        price: 5,
        goals: 0,
        points: 0,
        name: 'LeBlanc'
    }
];
